config/routes.rb
Rails.application.routes.draw do
  get    'login'  => 'sessions#new'
  delete 'logout' => 'sessions#destroy'

  root "products#index"

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews

  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}
  #####some side work####
  # validate :price_must_be_greater_than_5
  #
  # def price_must_be_greater_than_5
  #   if price_in_cents && price_in_cents < 5
  #     self.errors[:base] << "what ever"
  #   end
  # end

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :comment, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, :email, presence: true

  has_many :reviews
  has_many :products, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end

  def ensure_logged_in
    unless current_user
      flash[:alert] = 'Please login'
      redirect_to login_path
    end
  end
  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:search]
      @products = Product.where("name LIKE ?", "%#{params[:search]}%")
    else
      @products = Product.all
    end

    respond_to do |format|
      format.html
      format.js
    end
    # if request.xhr?
    #   render @products
    # end
  end

  def show
    @product = Product.find(params[:id])
    if current_user
      #@review = @product.reviews.build
      @review = Review.new(product: @product)
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
    redirect_to products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
    redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :ensure_logged_in, only: [:create, :destroy]
  before_action :load_product

  def show
    @review = Review.find(params[:id])
  end

  def create
    sleep(3)
    @review = @product.reviews.build(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product), notice: "review created successfully"}
        format.js {}
      else
        format.html {render product_path(@product), notice: "review was not created"}
        format.js {}
      end
    end
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in!"
    else
      render "new", notice: "Logged in failed!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Signed up!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="notification">
    <% if flash[:notice]%>
      <p id='notice'>
        <%= flash[:notice] %>
      </p>
    <% end %>
    <% if flash[:alert]%>
      <p id='alert'>
        <%= flash[:alert] %>
      </p>
    <% end %>


  </div>
  <div>
    <% if current_user %>
      You are logged in As <%= current_user.email %>
      <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </div>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, 'error') %></h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
    <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<p>
  <%= link_to product.name, product_path(product)%>
</p>
<p>
  <%= product.description%>
</p>
<p>
  <%= product.formatted_price%>
</p>

app/views/products/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<div class="link">
  <%= link_to "new", new_product_path%>
</div>
<%= form_tag products_path, method: :get, authentication: false, id: "search-form" do %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag 'Search' %>
<% end %>
<div id="products">
  <%= render @products %>
</div>

<!-- <script type="text/javascript">
function dispaly_search_results() {
  if (this.readyState === 4) {
    console.log(this);
    document.getElementById('products').innerHTML = this.responseText;
  }
}

var form = document.getElementById('search-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();
  var searchValue = document.getElementById('search').value;

  var xhr = new XMLHttpRequest();
  xhr.onload = dispaly_search_results;
  xhr.open('GET', '/products?search=' + searchValue, true);
  xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
  xhr.send();
})
</script> -->

app/views/products/index.js.erb
$('#products').html("<%= j(render @products)%>")

app/views/products/new.html.erb
<h1>New</h1>
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<div class="show">
  <p>
    <%= @product.name%>
  </p>
  <p>
    <%= @product.description%>
  </p>
  <p>
    <%= @product.formatted_price%>
  </p>
  <p>
    <%= link_to "remove", product_path(@product), method: :delete %>
    <%= link_to "edit", edit_product_path(@product) %>
  </p>
</div>


<div class="review_list">
  <h3>Comments</h3>
  <%= render @product.reviews %>
</div>


<% if current_user %>
  <h3>New Comment</h3>
  <%= form_for [ @product, @review], remote: true, html: {id: 'new_comment'} do |f| %>
    <div class="comment">
      <p><%= f.label :comment %></p>
      <p><%= f.text_area :comment %></p>
      <p ><%= f.submit %></p>
    </div>
  <% end %>
<% else %>
  <h4>Please <%= link_to "Log in", login_path %> to leave a comment</h4>
<% end %>

<script type="text/javascript">
  $(document).on('ready', function() {
    $("#new_comment").on('ajax:beforeSend', function () {
      $("input[type='submit']").val('Saving').attr('disabled', 'disabled');
    })
    $("#new_comment").on('ajax:complete', function () {
      $("input[type='submit']").val('Create Review');
      $("input[type='submit']").removeAttr('disabled');
      $("#new_comment").scrollTop();
    })
  })
</script>
<!-- <script type="text/javascript">

  $(document).ready(function() {
     $("#new_comment")
        .on('ajax:beforeSend', function() {alert("loading!");})
        .on('ajax:success', function(data, status, xhr) {alert("success!");})
        .on('ajax:error', function(xhr, status, error) {alert("error!");})
        .on('ajax:complete', function() {alert("complete!");});
  });

</script> -->

app/views/products/show.js.erb
$('body').append("<%= j(render @product) %>");

app/views/reviews/_review.html.erb
<li class= 'each_comment'>
  <p>
    <%= review.comment %>
  </p>
  <small>Commented by <%= review.user.email %></small>
</li>

app/views/reviews/_review_error_form.html.erb
<% @review.errors.full_messages.each do |error| %>
  <div class="error">
    <%= error %>
  </div>
<% end %>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $('.review_list').append("<%= j(render 'review_error_form') %>");
<% else %>
  $('.review_list').append($("<%= j(render @review) %>").css('color', 'red'));
  $(document).scrollTop($($('.each_comment')[$('.each_comment').size() -1]).position().top);
  $('#new_comment')[0].reset();
<% end %>

app/views/reviews/show.html.erb
<h1>Review#show</h1>
<p>Find me in app/views/review/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<%= link_to 'Back to Homepage', root_path %>

<%= form_for(@user) do |f|%>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end%>